config-version = 2
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]

[workspace-to-monitor-force-assignment]
    1 = 'built-in'
    2 = 'built-in'
    3 = 'built-in'
    4 = 'built-in'
    5 = 'built-in'
    6 = 'secondary'
    7 = 'secondary'
    8 = 'secondary'
    9 = 'secondary'
    0 = 'secondary'

on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 16
    inner.vertical =   16
    outer.left =       16
    outer.bottom =     16
    outer.top =        16
    outer.right =      16

[mode.main.binding]
    alt-h = ['focus --boundaries all-monitors-outer-frame left', 'move-mouse window-lazy-center']
    alt-j = ['focus --boundaries all-monitors-outer-frame down', 'move-mouse window-lazy-center']
    alt-k = ['focus --boundaries all-monitors-outer-frame up', 'move-mouse window-lazy-center']
    alt-l = ['focus --boundaries all-monitors-outer-frame right', 'move-mouse window-lazy-center']

    alt-shift-h = 'move --boundaries all-monitors-outer-frame left'
    alt-shift-j = 'move --boundaries all-monitors-outer-frame down'
    alt-shift-k = 'move --boundaries all-monitors-outer-frame up'
    alt-shift-l = 'move --boundaries all-monitors-outer-frame right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    ctrl-alt-shift-1 = 'workspace 1'
    ctrl-alt-shift-2 = 'workspace 2'
    ctrl-alt-shift-3 = 'workspace 3'
    ctrl-alt-shift-4 = 'workspace 4'
    ctrl-alt-shift-5 = 'workspace 5'
    ctrl-alt-shift-6 = 'workspace 6'
    ctrl-alt-shift-7 = 'workspace 7'
    ctrl-alt-shift-8 = 'workspace 8'
    ctrl-alt-shift-9 = 'workspace 9'
    ctrl-alt-shift-0 = 'workspace 0'

    cmd-alt-shift-1 = 'move-node-to-workspace --focus-follows-window 1'
    cmd-alt-shift-2 = 'move-node-to-workspace --focus-follows-window 2'
    cmd-alt-shift-3 = 'move-node-to-workspace --focus-follows-window 3'
    cmd-alt-shift-4 = 'move-node-to-workspace --focus-follows-window 4'
    cmd-alt-shift-5 = 'move-node-to-workspace --focus-follows-window 5'
    cmd-alt-shift-6 = 'move-node-to-workspace --focus-follows-window 6'
    cmd-alt-shift-7 = 'move-node-to-workspace --focus-follows-window 7'
    cmd-alt-shift-8 = 'move-node-to-workspace --focus-follows-window 8'
    cmd-alt-shift-9 = 'move-node-to-workspace --focus-follows-window 9'
    cmd-alt-shift-0 = 'move-node-to-workspace --focus-follows-window 0'

    ctrl-alt-shift-tab = 'workspace-back-and-forth'

    alt-shift-esc = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main']
    f = ['layout floating tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
