set -g mouse on
set -g history-limit 100000
set -g base-index 1
setw -g pane-base-index 1

set -g prefix C-a
unbind C-b
bind C-a send-prefix

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

set -g status-position bottom
set -g status-style fg=white,bg=black
setw -g allow-rename off
setw -g automatic-rename on
setw -g automatic-rename-format "#{?pane_current_command,#{pane_current_command},shell}"
set-hook -g after-new-window 'set -w automatic-rename on'
run-shell 'tmux list-windows -a -F "#{session_name}:#{window_index}" | xargs -I{} tmux set-window-option -t {} automatic-rename on >/dev/null 2>&1'
set -g status-left-length 100
set -g status-right-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

bind -n C-n next-window
bind -n C-p previous-window

bind - split-window -v -c "#{pane_current_path}"
bind _ split-window -h -c "#{pane_current_path}"
unbind '"'
unbind %

bind Q confirm-before -p "kill-session #S? (y/n)" kill-session
bind-key x kill-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_style 'rounded'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'

set -g window-status-format "#[fg=#11111b,bg=#{@thm_overlay_2}]#[fg=#181825,reverse]#[none]#I #[fg=#cdd6f4,bg=#{@thm_surface_0}] #{?pane_current_command,#{pane_current_command},shell}#[fg=#181825,reverse]#[none]"
set -g window-status-current-format "#[fg=#11111b,bg=#{@thm_mauve}]#[fg=#181825,reverse]#[none]#I #[fg=#cdd6f4,bg=#{@thm_surface_1}] #{?pane_current_command,#{pane_current_command},shell}#[fg=#181825,reverse]#[none]"
